name: build-package
on:
  push:
    paths:
    - '.github/workflows/build-package.yml'
    - 'build.sh'
    - 'laf'
  workflow_dispatch:
    inputs:
      os:
        description: 'Target operating system'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - windows-latest
        - macos-latest
        - ubuntu-latest
jobs:
  build-auto:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.event_name == 'workflow_dispatch' && [github.event.inputs.os] || [windows-latest, macos-latest, ubuntu-latest] }}
        # 只构建RelWithDebInfo版本
        build_type: ['RelWithDebInfo']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Install Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
          libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
    - uses: aseprite/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Building
      shell: bash
      run: |
        bash build.sh --auto --norun
    - name: Verify Build Output
      shell: bash
      run: |
        echo "Build directory contents:"
        ls -R build || true
    - name: Running CLI Tests
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        export ASEPRITE=$PWD/build/bin/aseprite
        cd tests
        $XVFB bash run-tests.sh
    - name: Package Artifacts
      shell: bash
      run: |
        BUILD_DIR="$PWD/build"
        ARTIFACT_NAME="aseprite-${{ runner.os }}"
        
        case "${{ runner.os }}" in
          Windows)
            # 查找Windows构建输出目录
            if [ -d "$BUILD_DIR/bin/RelWithDebInfo" ]; then
              OUTPUT_DIR="$BUILD_DIR/bin/RelWithDebInfo"
            elif [ -d "$BUILD_DIR/bin/Release" ]; then
              OUTPUT_DIR="$BUILD_DIR/bin/Release"
            else
              OUTPUT_DIR="$BUILD_DIR/bin"
            fi
            
            # 确保7z可用
            if ! command -v 7z &> /dev/null; then
              echo "Installing 7zip..."
              choco install 7zip -y
            fi
            
            # 创建ZIP文件
            7z a "$ARTIFACT_NAME.zip" "$OUTPUT_DIR/*"
            echo "ASSET_NAME=$ARTIFACT_NAME.zip" >> $GITHUB_ENV
            ;;
          macOS)
            tar czf "$ARTIFACT_NAME.tar.gz" -C "$BUILD_DIR/bin" .
            echo "ASSET_NAME=$ARTIFACT_NAME.tar.gz" >> $GITHUB_ENV
            ;;
          Linux)
            tar czf "$ARTIFACT_NAME.tar.gz" -C "$BUILD_DIR/bin" .
            echo "ASSET_NAME=$ARTIFACT_NAME.tar.gz" >> $GITHUB_ENV
            ;;
        esac
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET_NAME }}
        path: ${{ env.ASSET_NAME }}

  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: build-auto
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-build-${{ github.run_id }}
        name: "Autobuild #${{ github.run_number }} (${{ github.sha }})"
        body: |
          Automated build from CI
          - Trigger: ${{ github.event_name }}
          - Commit: ${{ github.sha }}
          - Build ID: ${{ github.run_id }}
          ${{ github.event_name == 'workflow_dispatch' && format('- Manual trigger by: {0}', github.actor) || '' }}
        draft: true
        prerelease: false
        files: artifacts/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
