name: build-package
on:
  push:
    paths:
    - '.github/workflows/build-package.yml'
    - 'build.sh'
    - 'laf'
  workflow_dispatch:
    inputs:
      os:
        description: 'Target operating system'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
        - windows-latest
        - macos-latest
        - ubuntu-latest
jobs:
  build-auto:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(github.event_name == 'workflow_dispatch' && format('["{0}"]', github.event.inputs.os) || '["windows-latest", "macos-latest", "ubuntu-latest"]') }}
        build_type: ['RelWithDebInfo']
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - name: Clone strings repository (full history)
      shell: bash
      run: |
        mkdir -p data
        git clone https://github.com/aseprite/strings.git temp-strings
    - name: Install Dependencies
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
          libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev
    - uses: aseprite/get-ninja@main
    - uses: ilammy/msvc-dev-cmd@v1
      if: runner.os == 'Windows'
    - name: Building
      shell: bash
      run: |
        bash build.sh --auto --norun
        
    - name: Copy strings to data directory
      shell: bash
      run: |
        # 确保data目录存在
        mkdir -p build/bin/data
        
        # 复制strings仓库内容到data/strings
        cp -r temp-strings build/bin/data/strings    
    - name: Running CLI Tests
      shell: bash
      run: |
        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export XVFB=xvfb-run
        fi
        export ASEPRITE=$PWD/build/bin/aseprite
        cd tests
        $XVFB bash run-tests.sh
    - name: Package Artifacts
      shell: bash
      run: |
        BUILD_DIR="$PWD/build"
        ARTIFACT_NAME="aseprite-${{ runner.os }}"
        
        case "${{ runner.os }}" in
          Windows)
            # 确保7z可用
            if ! command -v 7z &> /dev/null; then
              echo "Installing 7zip..."
              choco install 7zip -y
            fi
            
            # 直接使用build/bin目录
            cd "$BUILD_DIR/bin"
            
            # 创建ZIP文件，包含所有内容
            7z a "$ARTIFACT_NAME.zip" *
            
            # 移动ZIP文件到工作目录
            mv "$ARTIFACT_NAME.zip" "$GITHUB_WORKSPACE/"
            cd "$GITHUB_WORKSPACE"
            
            echo "ASSET_NAME=$ARTIFACT_NAME.zip" >> $GITHUB_ENV
            ;;
          macOS)
            cd "$BUILD_DIR/bin"
            tar czf "$ARTIFACT_NAME.tar.gz" *
            mv "$ARTIFACT_NAME.tar.gz" "$GITHUB_WORKSPACE/"
            cd "$GITHUB_WORKSPACE"
            echo "ASSET_NAME=$ARTIFACT_NAME.tar.gz" >> $GITHUB_ENV
            ;;
          Linux)
            cd "$BUILD_DIR/bin"
            tar czf "$ARTIFACT_NAME.tar.gz" *
            mv "$ARTIFACT_NAME.tar.gz" "$GITHUB_WORKSPACE/"
            cd "$GITHUB_WORKSPACE"
            echo "ASSET_NAME=$ARTIFACT_NAME.tar.gz" >> $GITHUB_ENV
            ;;
        esac
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ASSET_NAME }}
        path: ${{ env.ASSET_NAME }}

  create-release:
    name: Create Draft Release
    runs-on: ubuntu-latest
    needs: build-auto
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        # 添加这个选项，将所有工件合并到一个目录中
        merge-multiple: true
    - name: List Downloaded Artifacts
      run: |
        echo "Artifacts directory contents:"
        ls -la artifacts/
        echo "All files in artifacts directory:"
        find artifacts/ -type f
    - name: Create Draft Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-build-${{ github.run_id }}
        name: "Autobuild #${{ github.run_number }} (${{ github.sha }})"
        body: |
          Automated build from CI
          - Trigger: ${{ github.event_name }}
          - Commit: ${{ github.sha }}
          - Build ID: ${{ github.run_id }}
          ${{ github.event_name == 'workflow_dispatch' && format('- Manual trigger by: {0}', github.actor) || '' }}
        draft: true
        prerelease: false
        # 使用更具体的文件模式
        files: |
          artifacts/aseprite-Windows.zip
          artifacts/aseprite-Linux.tar.gz
          artifacts/aseprite-macOS.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
